services:
  git-workspace-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: denghui/git-workspace-agent:251031
    env_file:
      - .env
    environment:
      HOST_WORKSPACE_DIR: ${HOST_WORKSPACE_DIR:-/tmp/git-workspace-agent}
    volumes:
      - ${HOST_WORKSPACE_DIR:-/tmp/git-workspace-agent}:${HOST_WORKSPACE_DIR:-/tmp/git-workspace-agent}
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    # ports:
    #   - "${EXPOSED_PORT:-7213}:7213"
    restart: unless-stopped
    command: ["uvicorn", "git_workspace_agent.server:app", "--host", "0.0.0.0", "--port", "${EXPOSED_PORT:-7213}"]